## name: evergarden summer yellow
## author: comfysage
## license: GPL-3.0
## blurb: a comfy colorscheme for cozy morning coding

foreground               #2b3034
background               #f5efe6
selection_foreground     #2b3034
selection_background     #e6e1d3

wayland_titlebar_color   #e8ded5
macos_titlebar_color     #e8ded5

cursor                   #c4aa80
cursor_text_color        #e8ded5

url_color                #8294ad

active_tab_foreground    #e8ded5
active_tab_background    #c4aa80

inactive_tab_foreground  #829084
inactive_tab_background  #171c1f

# black
color0   #e6e1d3
color8   #829084

# red
color1   #c58687
color9   #c58687

# green
color2   #91a77a
color10  #91a77a

# yellow
color3   #c4aa80
color11  #c4aa80

# blue
color4   #8294ad
color12  #8294ad

# purple
color5   #c499b8
color13  #c499b8

# aqua
color6   #74a48b
color14  #74a48b

# white
color7   #576869
color15  #455355
