# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-e60a6248-6e30-4d4f-9eb2-1223346cc332";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-e60a6248-6e30-4d4f-9eb2-1223346cc332".device = "/dev/disk/by-uuid/e60a6248-6e30-4d4f-9eb2-1223346cc332";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A9B6-F67D";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-4d3dca95-cccf-48da-b970-cae48ccecfd9"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
